name: AFMCorePlugin
version: ${project.version}
main: ru.iterator.afmcp.AFMCorePlugin
commands:
  createpreset:
    description: Создать ашблон сундука
    usage: /createpreset <имя БЕЗ пробелов>
  setchest:
    description: Установить сундуку шаблон
    usage: /setchest <имя шаблона БЕЗ пробелов>
  deletepreset:
    description: Удалить ашблон сундука
    usage: /deletepreset <имя БЕЗ пробелов>
  unsetchest:
    description: Удалить шаблон с сундука.
    usage: /unsetchest
  soicp:
    description: Информация/перезагрузка/дебаг SOICP Native
    usage: /afmcp [reload/debug]
