name: AFMCorePlugin
main: ru.allformine.afmcp.AFMCorePlugin
version: 1.5.2
author: Iterator
depend: [ProtocolLib, VanishNoPacket, Herochat]
softdepend: [Factions]
commands:
  afmcp:
    description: Тестовая комаеда, хыыы
    usage: /afmcp
  freeze:
    description: Заморозить игрока.
    usage: "Использование: /freeze <ник>"
    permission: afmcp.staff
    permission-message: У тебя нет прав, иди нахуй, бля.
  rawbc:
    description: Отправить сообщение в таком виде, в котором вы его написали.
    usage: "Использование: /rawbc <сообщение>"
    permission: afmcp.staff
    permission-message: У тебя нет прав, иди нахуй, бля.
  notify:
    description: Отослать уведомление в оверлей всем игрокам.
    usage: "Использование: /notify <сообщение не больше 48 символов>"
    permission: afmcp.staff
    permission-message: У тебя нет прав, иди нахуй, бля.
  vip:
    description: Купить VIP-статус
    usage: "Использование: /vip <Alpha | Beta | Gamma>"
  tokens:
    description: Посмотреть, сколько токенов на счету.
    usage: "Использование: /tokens"
  afmreload:
    description: Перезагрузить конфигурацию плагина.
    usage: "Использование: /afmreload"
    permission: afmcp.reload
    permission-message: У тебя нет прав, иди нахуй, бля.
