name: AFMCorePlugin
main: ru.allformine.afmcp.AFMCorePlugin
version: 1.8
author: Iterator
depend: [ProtocolLib, VanishNoPacket, Herochat]
softdepend: [Factions]
commands:
  afmcp:
    description: Тестовая комаеда, хыыы
    usage: /afmcp
  freeze:
    description: Заморозить игрока.
    usage: "Использование: /freeze <ник>"
    permission: afmcp.staff
    permission-message: У тебя нет прав, иди нахуй, бля.
  rawbc:
    description: Отправить сообщение в таком виде, в котором вы его написали.
    usage: "Использование: /rawbc <сообщение>"
    permission: afmcp.staff
    permission-message: У тебя нет прав, иди нахуй, бля.
  notify:
    description: Отослать уведомление в оверлей всем игрокам.
    usage: "Использование: /notify <сообщение не больше 48 символов>"
    permission: afmcp.staff
    permission-message: У тебя нет прав, иди нахуй, бля.
  notifyplayer:
    description: Отослать уведомление в оверлей игроку.
    usage: "Использование: /notifyplayer <игрок> <сообщение не больше 48 символов>"
    permission: afmcp.staff
    permission-message: У тебя нет прав, иди нахуй, бля.
  vip:
    description: Купить VIP-статус
    usage: "Использование: /vip <Alpha | Beta | Gamma>"
  tokens:
    description: Посмотреть, сколько токенов на счету.
    usage: "Использование: /tokens"
  afmreload:
    description: Перезагрузить конфигурацию плагина.
    usage: "Использование: /afmreload"
    permission: afmcp.reload
    permission-message: У тебя нет прав, иди нахуй, бля.
  gift:
    description: Получить новогодний подарок.
    usage: "Использование: /gift"
  afmcplog:
    description: Включить/выключить логгирование в дискорд.
    usage: "Использование: /afmcplog <true|false>"
    permission: afmcp.log
    permission-message: У тебя нет прав, иди нахуй, бля.
  maintenance:
    description: Включить/выключить режим тех.работ на сервере
    usage: "Использование: /maintenance <true|false>"
    permission: afmcp.maintenance
    permission-message: У тебя нет прав, иди нахуй, бля.